---
node:
- node/10
- node/12
- node/14
- node/16
- node/18
- node/20
- node/22
- node/24
- node/25
- node/8
core:
- core/bionic
- core/jammy
- core/noble
ruby:
- ruby/2.4
- ruby/2.5
- ruby/2.6
- ruby/2.7
- ruby/3.0
- ruby/3.1
- ruby/3.2
- ruby/3.3
- ruby/3.4
- ruby/4.0
