name: Cleanup intermediate tags

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday
  workflow_dispatch: {}

permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [core, ruby, node]
    steps:
      - name: Debug API response
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/users/djbender/packages/container/${{ matrix.package }}
      - uses: snok/container-retention-policy@v3.0.1
        with:
          account: djbender
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: ${{ matrix.package }}
          cut-off: 1w
          # Delete intermediate arch-specific build tags (e.g. jammy-1234567890-amd64)
          image-tags: "*-amd64 *-arm64"
          tag-selection: tagged
          keep-n-most-recent: 0
