name: Cleanup intermediate tags

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday
  workflow_dispatch: {}

permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    concurrency:
      group: cleanup-packages
    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: core,ruby,node
          delete-tags: '*-amd64,*-arm64'
          delete-untagged: true
          older-than: 4 weeks
          delete-ghost-images: true
          delete-partial-images: true
          delete-orphaned-images: true
