name: Cleanup intermediate tags

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday
  workflow_dispatch: {}

permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [core, ruby, node]
    steps:
      - uses: snok/container-retention-policy@v3.0.1
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: ${{ matrix.package }}
          cut-off: 1w
          # Delete intermediate arch-specific build tags (e.g. jammy-1234567890-amd64)
          image-tags: "*-amd64 *-arm64"
          tag-selection: tagged
          keep-n-most-recent: 0
          dry-run: true
